function DebugPose(obj, frameNumber)
%debugPose.m Graphs a pose
%   poseData:     20x3 array of joint data
    
    % graph axes...
    gx=1;
    gy=3;
    gz=2;
    
	head_spine_hips=vertcat(...
		obj.getJointData(frameNumber, 'HEAD'), ...
		obj.getJointData(frameNumber, 'SHOULDER_C'), ...
		obj.getJointData(frameNumber, 'SPINE'), ...
		obj.getJointData(frameNumber, 'HIP_C') ...
	);

	hand_to_hand=vertcat(...
		obj.getJointData(frameNumber, 'HAND_L'), ...
		obj.getJointData(frameNumber, 'WRIST_L'), ...
		obj.getJointData(frameNumber, 'ELBOW_L'), ...
		obj.getJointData(frameNumber, 'SHOULDER_L'), ...
		obj.getJointData(frameNumber, 'SHOULDER_C'), ...
		obj.getJointData(frameNumber, 'SHOULDER_R'), ...
		obj.getJointData(frameNumber, 'ELBOW_R'), ...
		obj.getJointData(frameNumber, 'WRIST_R'), ...
		obj.getJointData(frameNumber, 'HAND_R') ...
	);

	foot_to_foot=vertcat(...
		obj.getJointData(frameNumber, 'FOOT_L'), ...
		obj.getJointData(frameNumber, 'ANKLE_L'), ...
		obj.getJointData(frameNumber, 'KNEE_L'), ...
		obj.getJointData(frameNumber, 'HIP_L'), ...
		obj.getJointData(frameNumber, 'HIP_C'), ...
		obj.getJointData(frameNumber, 'HIP_R'), ...
		obj.getJointData(frameNumber, 'KNEE_R'), ...
		obj.getJointData(frameNumber, 'ANKLE_R'), ...
		obj.getJointData(frameNumber, 'FOOT_R') ...
	);
    

    plot3(...
		foot_to_foot(:, gx), foot_to_foot(:, gy), foot_to_foot(:, gz), '-s', ...   
		hand_to_hand(:, gx), hand_to_hand(:, gy), hand_to_hand(:, gz), '-s', ...
		head_spine_hips(:, gx), head_spine_hips(:, gy), head_spine_hips(:, gz), '-s' ...
	);
    axis equal;
	
	slack=0.2;
	slackVec=[-slack, slack];
	if isfield(obj.debugDimensions, 'X') == 0
		obj.debugDimensions.X=get(gca,'XLim');
		obj.debugDimensions.Y=get(gca,'YLim');
		obj.debugDimensions.Z=get(gca,'ZLim');
		obj.debugDimensions.X=obj.debugDimensions.X+slackVec;
		obj.debugDimensions.Y=obj.debugDimensions.Y+slackVec;
	end
		set(gca,'XLim', obj.debugDimensions.X);
		set(gca,'YLim', obj.debugDimensions.Y);
		set(gca,'ZLim', obj.debugDimensions.Z);

			
end