function elbowshoulder_R = f_elbowAngle_R(obj, frameNumber)
	UpperAVector=obj.getJointData(frameNumber, 'ELBOW_R') ...
		-obj.getJointData(frameNumber, 'SHOULDER_R');
	ForeAVector=obj.getJointData(frameNumber, 'WRIST_R') ...
		-obj.getJointData(frameNumber, 'ELBOW_R');
    
    elbowshoulder_R =180-acos(...
        dot(UpperAVector, ForeAVector)./(...
        norm(UpperAVector)*norm(ForeAVector)...
        ))*(180/pi);
end