function elbowshoulder_L = f_elbowAngle_L(obj, frameNumber)
	UpperAVector=obj.getJointData(frameNumber, 'ELBOW_L') ...
		-obj.getJointData(frameNumber, 'SHOULDER_L');
	ForeAVector=obj.getJointData(frameNumber, 'WRIST_L') ...
		-obj.getJointData(frameNumber, 'ELBOW_L');
    
    elbowshoulder_L =180-acos(...
        dot(UpperAVector, ForeAVector)./(...
        norm(UpperAVector)*norm(ForeAVector)...
        ))*(180/pi);
end