function headpitch = f_headpitch(obj, frameNumber)
	HeadVector=obj.getJointData(frameNumber, 'HEAD') ...
		-obj.getJointData(frameNumber, 'SHOULDER_C');
	BackVector=obj.getJointData(frameNumber, 'SHOULDER_C') ...
		-obj.getJointData(frameNumber, 'SPINE');
    
    headpitch =180-acos(...
        dot(HeadVector, BackVector)./(...
        norm(HeadVector)*norm(BackVector)...
        ))*(180/pi);
end