function angleHip = f_hipAngle_R(obj, frameNumber)
	hips=vertcat(...
		obj.getJointData(frameNumber, 'HIP_L'), ...
		obj.getJointData(frameNumber, 'HIP_C'), ...
		obj.getJointData(frameNumber, 'HIP_R') ...
    );
    
    endpts1=obj.bestFitLine3d(hips);
    hipVector=endpts1(1, :)-endpts1(2, :);
    hipVector(:, 2) = 0; %% reduce y dimensionality
    
    kneeVector=obj.getJointData(frameNumber, 'HIP_R')-obj.getJointData(frameNumber, 'KNEE_R');
    kneeVector(:, 2) = 0; %% reduce y dimensionality
    
    angleHip=180-acos(...
        dot(hipVector, kneeVector)./(...
        norm(hipVector)*norm(kneeVector)...
        ))*(180/pi);
    
end


