function angleKnee = f_kneeAngle(obj, frameNumber)
	shinVector=obj.getJointData(frameNumber, 'KNEE_R') ...
		-obj.getJointData(frameNumber, 'ANKLE_R');
	thighVector=obj.getJointData(frameNumber, 'HIP_R') ...
		-obj.getJointData(frameNumber, 'KNEE_R');
    
    angleKnee=180-acos(...
        dot(shinVector, thighVector)./(...
        norm(shinVector)*norm(thighVector)...
        ))*(180/pi);
end


