function spineCurl_pitch = f_spineCurl_pitch(obj, frameNumber)
	UpperSpine=obj.getJointData(frameNumber, 'SHOULDER_C') ...
		-obj.getJointData(frameNumber, 'SPINE');
	LowerSpine=obj.getJointData(frameNumber, 'SPINE') ...
		-obj.getJointData(frameNumber, 'HIP_C');
    
	% Only look at the tilt
	UpperSpine(1)=0; LowerSpine(1)=0;
	
    spineCurl_pitch =180-acos(...
        dot(UpperSpine, LowerSpine)./(...
        norm(UpperSpine)*norm(LowerSpine)...
        ))*(180/pi);
end