function spineCurl_tilt = f_spineCurl_tilt(obj, frameNumber)
	UpperSpine=obj.getJointData(frameNumber, 'SHOULDER_C') ...
		-obj.getJointData(frameNumber, 'SPINE');
	LowerSpine=obj.getJointData(frameNumber, 'SPINE') ...
		-obj.getJointData(frameNumber, 'HIP_C');
    
	% Only look at the tilt
	UpperSpine(3)=0; LowerSpine(3)=0;
	
    spineCurl_tilt =180-acos(...
        dot(UpperSpine, LowerSpine)./(...
        norm(UpperSpine)*norm(LowerSpine)...
        ))*(180/pi);
end