function features = poseFeatures(obj, frameNumber)
	features=[...
		obj.f_hipAngle(obj, frameNumber),...
		obj.f_kneeAngle(obj, frameNumber), ...
		obj.f_spineStability(obj, frameNumber), ...
		obj.f_elbowAngle_L(obj, frameNumber), ...
		obj.f_elbowAngle_R(obj, frameNumber), ...
		obj.f_headtilt(obj, frameNumber), ...
		obj.f_headpitch(obj, frameNumber), ...
		obj.f_ankleLevel(obj, frameNumber), ...
		obj.f_handLevel(obj, frameNumber), ...
		obj.f_hipLevel(obj, frameNumber), ...
		obj.f_shoulderLevel(obj, frameNumber), ...
		0,0,0,0 ...
	];

	obj.featureVector=features;
end